### ISSUE TITLE
Build a tablebot

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/stm32#8]
# Components

 * [x] Etherbotix, with MD-03 motor driver, Mini-IMU v5
 * [x] 3 Cliff sensors (GP2Y0D805Z0F) on height adjustable bracket
 * [x] Differential drive - QTY2 12v 30:1 200RPM motors
 * [x] LD-06 Lidar
 * [x] AX-12 servo to tilt lidar (mounted on left side to avoid interfering with the lidar cable)
 * [x] 12V, 3Ah battery

# Roadmap

 * [x] Verify that laser works at high angle of incidence (just use ROS drivers)
 * [x] Get laser driver working on Etherbotix, just fill in 360 degree polar map, send over ethernet, visualize on desktop
 * [x] Design, 3d print and assemble physical chassis
 * [x] Tune PID for motors, make sure we can travel a set distance
 * [x] Tune odometry, make sure 90 degree turns are good
 * [x] Tune cliff sensors
 * [x] Phase 1A - drive straight until cliff sensors trigger, back up, turn 180, repeat
 * [x] Add debugging data over ethernet: odometry pose estimate
 * [x] Add visualization of debugging data
 * [x] Get debugging data over wifi
 * [x] Selection of phases using IMU
 * [x] Get servo running
 * [x] Phase 1B - put control loop around Y error to keep us more centered on the table
 * [x] Phase 1C - Use laser to detect cliff ahead of time (so we can go faster)
 * [ ] Phase 1D - Use laser to detect the width of table and keep robot centered
 * [x] Phase 2A - sweep laser and assemble scan
 * [x] Phase 2B - find block in laser scan
 * [x] Phase 2C - approach block and push off table
 * [x] Phase 3A - find box using level laser
 * [x] Phase 3B - change block target pose so that we can push block to goal even if it is off to side of table
 * [x] Phase 3C - push block into box (behavior is present, but only works well if block is fairly closet to middle of table)
 * [x] Physically rotate laser 180 degrees so that we can segment scans for block detection while moving (currently, discontinuity is in the front center, this would put it in the back). Also requires update to transform code in robot and viewer.

Open Issues
 * [x] ~~Bootloader won't boot after upload - requires a power cycle?~~ Has gone away after fixing LD06 driver.
 * [x] ~~Need to add CRC to LD06 driver~~
 * [x] ~~Odometry is off - Y axis is inverted (we're fixing this by inverting Y in the struct unpack)~~
 * [x] ~~TIM12/PWM seems very off - is this actually up-down counting? That would explain the prescalar issue and also why the "40%" PWM drives laser so slow (check on scope if it is actually 40% or 20%)~~ - nope, it checks out at 40% - no idea why we need to output 70% to get the proper rotation speed
 * [x] ~~Won't run without the ethernet cable plugged in~~

Known Issues
 * [x] Can't receive packets bigger than MTU. They show up in Wireshark (which doesn't process checksums) but doesn't show up in python socket.recv() - still exists but packets are now broken up to be smaller than MTU

**Comment by mikeferguson** [comment]
Tested laser using https://github.com/AlessioMorale/ld06_lidar:

1. With laser about 4" above table surface, tilted 90 degrees down, it can see the full 4 ft length of my test table
2. With laser about 4" above table surface, tilted about 90 degrees down, the unbounded cube appears clearly

**Comment by mikeferguson** [comment]
* Encoders are terminated, validated for ticks/rev
 * PWM output for lidar is correct frequency (29.8khz)
 * Lidar data is being received - need to implement CRC

**Comment by mikeferguson** [comment]
- Fully assembled and wired up
- Cliff sensors validated - looks like they will work well
- Current consumption with all components, but no motion is 267mA @ 12v (3.2W)

**Comment by mikeferguson** [comment]
Phase 1 works - pure odometry + cliff sensors. Requires ethernet cable plugged in... need to still debug that.

**Comment by mikeferguson** [comment]
Laser driver working, rendering in GUI
![image](https://user-images.githubusercontent.com/899410/226076311-5b42b511-3f21-424d-86e4-fb1f992652df.png)
